- name: Test dummy ServiceNow inventory
  hosts: all
  gather_facts: false
  tasks:
    - name: Show fake host info
      debug:
        msg: "Host: {{ inventory_hostname }}, IP: {{ ansible_host }}, sys_id: {{ sn_sys_id }}"
